FROM rust:1.88.0

WORKDIR /app
COPY . .

RUN cargo build --release

ENV BASE_URL=${BASE_URL}
ENV PORT=${PORT}
ENV API_KEY=${API_KEY}
ENV ADMIN_API_KEY=${ADMIN_API_KEY}
ENV POSTGRES_URL=${POSTGRES_URL}
ENV WEBHOOK_URL=${WEBHOOK_URL}
ENV FEATURES=${FEATURES}

CMD ["./target/release/query_api"]
